set pod security context for application deployment
mattermost/mattermost-helm pull request #208
Opened 2021-02-10 23:54 UTC by mrparkers

#### Summary

This PR allows users to configure the application pod's security context, which is required in order to persist changes to the filesystem for plugins and user data.

#### Ticket Link

Fixes #203

2021-02-10 23:54 UTC, mattermod commented
Hello @mrparkers,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2021-02-10 23:56 UTC, mrparkers commented
/check-cla

2021-02-15 22:16 UTC, jfrerich commented
@metanerd, is this something that you can take a look at?

2021-02-16 20:23 UTC, khos2ow reviewed
From the functional changes in this PR, it LGTM, but I'm not entirely sure why it's needed. What has changed in 5.30 which caused this change to be needed?

2021-02-25 21:04 UTC, mrparkers commented
Hey @khos2ow, thanks for the reply.  To my knowledge, there weren't any changes within the mattermost application that warrant this suggested change I'm making.  I started working with mattermost a few weeks ago, and found these issues when trying to install the chart for the first time using the default settings.  I'll try and be a bit more clear about the problems I'm trying to solve.

## Problem 1:
When you run the chart as-is with the default settings, depending on the version of Kubernetes you're using (I'm using AWS EKS 1.16 here), you may end up with an install in which the `/mattermost/data` and `/mattermost/plugins` folders are owned by the `root` user/group, and are write protected.  This results in the following log message when the pod first starts:

```
{"level":"error","ts":1614276004.08384,"caller":"app/plugin.go:824","msg":"Failed to install prepackaged plugin","path":"/mattermost/prepackaged_plugins/mattermost-plugin-nps-v1.1.0-linux-amd64.tar.gz","error":"Failed to install extracted prepackaged plugin /mattermost/prepackaged_plugins/mattermost-plugin-nps-v1.1.0-linux-amd64.tar.gz: installExtractedPlugin: Unable to move plugin from temporary directory to final destination. Another plugin may be using the same directory name., mkdir plugins/com.mattermost.nps: permission denied","errorVerbose":"installExtractedPlugin: Unable to move plugin from temporary directory to final destination. Another plugin may be using the same directory name., mkdir plugins/com.mattermost.nps: permission denied\nFailed to install extracted prepackaged plugin /mattermost/prepackaged_plugins/mattermost-plugin-nps-v1.1.0-linux-amd64.tar.gz\ngithub.com/mattermost/mattermost-server/v5/app.(*App).processPrepackagedPlugin\n\tgithub.com/mattermost/mattermost-server/v5/app/plugin.go:876\ngithub.com/mattermost/mattermost-server/v5/app.(*App).processPrepackagedPlugins.func2\n\tgithub.com/mattermost/mattermost-server/v5/app/plugin.go:822\nruntime.goexit\n\truntime/asm_amd64.s:1373"}
```

If you get a shell to the running container (via `kubectl exec`), you can see that the filesystem looks like this:

```
~ $ pwd
/mattermost
~ $ ls -alh
total 232K
drwxr-sr-x    1 mattermo mattermo      40 Feb 25 18:03 .
drwxr-xr-x    1 root     root          46 Feb 25 17:59 ..
-rw-------    1 mattermo mattermo      15 Feb 25 18:03 .ash_history
-rw-r--r--    1 mattermo mattermo    1.2K Nov 13 18:25 MIT-COMPILED-LICENSE.md
-rw-r--r--    1 mattermo mattermo  197.3K Nov 13 18:25 NOTICE.txt
-rw-r--r--    1 mattermo mattermo    5.4K Nov 13 18:25 README.md
drwxr-xr-x    2 mattermo mattermo      53 Nov 13 18:44 bin
drwxr-xr-x    1 mattermo mattermo     196 Nov 13 18:44 client
drwxr-xr-x    2 mattermo mattermo      42 Feb 25 17:59 config
drwxr-xr-x    3 root     root        4.0K Feb 25 17:57 data
drwxr-xr-x    2 mattermo mattermo      44 Nov 13 18:44 fonts
drwxr-xr-x    2 mattermo mattermo     255 Nov 13 18:44 i18n
drwxr-xr-x    2 mattermo mattermo      28 Feb 25 17:59 logs
drwxr-xr-x    3 root     root        4.0K Feb 25 17:57 plugins
drwxr-xr-x    2 mattermo mattermo    4.0K Nov 13 18:45 prepackaged_plugins
drwxr-xr-x    2 mattermo mattermo    4.0K Nov 13 18:44 templates
~ $ whoami
mattermost
```

As you can see, these folders aren't going to be writable to the currently logged in user.  So this means that the default plugin install process on initial startup won't work, and installing new plugins won't work either, as seen here:

![image](https://user-images.githubusercontent.com/3793752/109197219-57e41d80-7762-11eb-9a92-24425e735a3c.png)

Which also produces the following log message:

```
{"level":"error","ts":1614276544.0832715,"caller":"mlog/log.go:229","msg":"Unable to move plugin from temporary directory to final destination. Another plugin may be using the same directory name.","path":"/api/v4/plugins/marketplace","request_id":"7qgu8tuzt3r37gut9uod14cnfc","ip_addr":"10.16.115.64","user_id":"e5bt3aj557rp3ccjogqh5nxgyy","method":"POST","err_where":"installExtractedPlugin","http_code":500,"err_details":"mkdir plugins/com.github.moussetc.mattermost.plugin.giphy: permission denied"}
```

This also causes issues with persisting user profile data, as seen by the following log message after a user registers:

```
{"level":"error","ts":1614276521.279308,"caller":"mlog/log.go:229","msg":"Encountered an error creating the directory for the new file.","path":"/api/v4/users/e5bt3aj557rp3ccjogqh5nxgyy/image","request_id":"nk5wokdjsfgjzpc1e8ms6diama","ip_addr":"10.16.115.64","user_id":"e5bt3aj557rp3ccjogqh5nxgyy","method":"GET","err_where":"WriteFile","http_code":500,"err_details":"directory=/mattermost/data/users/e5bt3aj557rp3ccjogqh5nxgyy, err=mkdir data/users: permission denied"}
```

---

After the `securityContext` changes proposed in this PR, the filesystem instead looks like this (notice the group change for the `plugins` and `data` folders):

```
~ $ pwd
/mattermost
~ $ ls -alh
total 232K
drwxr-sr-x    1 mattermo mattermo      40 Feb 25 20:10 .
drwxr-xr-x    1 root     root          46 Feb 25 20:08 ..
-rw-------    1 mattermo mattermo      12 Feb 25 20:10 .ash_history
-rw-r--r--    1 mattermo mattermo    1.2K Nov 13 18:25 MIT-COMPILED-LICENSE.md
-rw-r--r--    1 mattermo mattermo  197.3K Nov 13 18:25 NOTICE.txt
-rw-r--r--    1 mattermo mattermo    5.4K Nov 13 18:25 README.md
drwxr-xr-x    2 mattermo mattermo      53 Nov 13 18:44 bin
drwxr-xr-x    1 mattermo mattermo     196 Nov 13 18:44 client
drwxr-xr-x    2 mattermo mattermo      42 Feb 25 20:08 config
drwxrwsr-x    4 root     mattermo    4.0K Feb 25 20:08 data
drwxr-xr-x    2 mattermo mattermo      44 Nov 13 18:44 fonts
drwxr-xr-x    2 mattermo mattermo     255 Nov 13 18:44 i18n
drwxr-xr-x    2 mattermo mattermo      28 Feb 25 20:08 logs
drwxrwsr-x    4 root     mattermo    4.0K Feb 25 20:08 plugins
drwxr-xr-x    2 mattermo mattermo    4.0K Nov 13 18:45 prepackaged_plugins
drwxr-xr-x    2 mattermo mattermo    4.0K Nov 13 18:44 templates
~ $ whoami
mattermost
```

Which allows the plugin to be installed successfully:

![image](https://user-images.githubusercontent.com/3793752/109211167-7acafd80-7773-11eb-8094-5d1e20bb005c.png)


And, the user data is persisting as expected.

## Problem 2:
With the fixes described above, the `gif` plugin can be installed, but it can not be configured from the UI:

![image](https://user-images.githubusercontent.com/3793752/109211422-d1d0d280-7773-11eb-969c-8a8504cb4aa8.png)

This emits the following log message:

```
{"level":"error","ts":1614284051.381758,"caller":"mlog/log.go:229","msg":"An error occurred saving the configuration.","path":"/api/v4/config","request_id":"1jzb9x83ztb5i88j4dbjs4g7ew","ip_addr":"10.16.119.117","user_id":"y84dbz4ziibwjndtf3ofpmdtma","method":"PUT","err_where":"saveConfig","http_code":500,"err_details":"failed to persist: failed to write file: open /mattermost/config/config.json: read-only file system"}
```

This is happening because the volume containing the `config.json` file is being created from a Kubernetes secret, resulting in a read-only filesystem.  While the docs suggest that you can mount this volume with any mode you want (perhaps `0644`), this issue indicates that this does not appear to be true: https://github.com/kubernetes/kubernetes/issues/62099.  When mounting from a secret, the `config.json` file in the filesystem will always look like this:

```
~/config $ pwd
/mattermost/config
~/config $ ls -alh
total 12K
drwxr-xr-x    2 mattermo mattermo      42 Feb 25 20:47 .
drwxr-sr-x    1 mattermo mattermo      40 Feb 25 20:48 ..
-rw-r--r--    1 mattermo mattermo     243 Nov 13 18:25 README.md
-rw-r--r--    1 root     mattermo    5.5K Feb 25 20:45 config.json
```

So, the only way to allow the mattermost application to modify this file is to change the way we're persisting it - using a volume that can be mounted as a writable filesystem.  The approach in this PR checks if `persistence.config.enabled` is set to `true` - if it is, we'll treat the `configJSON` value as an [...]

2021-03-07 15:22 UTC, agusl88 commented
I just tested this PR on my installation and worked perfectly, the config.json was initializated from the secrets and copied into the new persistentVolume and now all settings are writable from the System Console. 

The plugin marketplace also works and persist plugins withouth any issues.

2021-03-12 18:16 UTC, khos2ow reviewed
Thank you @mrparkers for the in-depth explanation and apologize for late response. I'm completely fine with the your proposed changed, however

> However, this approach comes at a cost - as the configJSON value will only be respected on the initial helm install. Users won't be able to use helm to further configure the application, only the UI

this seems to be a bit alarming, and definitely needs more eyes on it.

/cc @stylianosrigas @cpanato @jwilander

2021-03-12 20:40 UTC, mrparkers commented
Appreciate the response @khos2ow.  I just want to reiterate that the config persistence changes are only optional - the default value for config persistence is the functionality that's currently in master.  If it would help, I can document this change in the README, and clarify the tradeoff that comes with opting into this functionality.

For what it's worth, I've been using this version of the chart for a few weeks now, and I personally think it's a better experience managing these settings in the UI or even the Mattermost API rather than manually editing the `config.json` file (especially for plugin settings).

Anyways, please let me know if there's any way I can help move this along.  Thanks! 🚀

2021-03-12 20:44 UTC, khos2ow commented
That's great and I completely understand where you're coming from on this matter, but I, personally, am not in a position to call a final shot of this matter, specially that this scopes a bit beyond the chart and deployment itself and moves a bit into underlying config management of Mattermost as a whole.

2021-03-14 04:03 UTC, agusl88 commented
Maybe setting the toggle off by default is the best approach, since it wont forcefully change the way of handling the config.json for people that is already using the chart.

Imo the ideal solution would be to move the plugins configuration out of the config.json, so we can manage the server settings via the helm-deployment while having the plugin marketplace functional, but i believe that's a suggestion that would have to be done to the core repository. In the meantime, this change seems like a good workaround to avoid breaking the plugin marketplace for everyone using this chart withouth giving them an easy way to fix the problem

2021-03-25 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-04-20 15:46 UTC, Blackclaws commented
Why is this still not merged if I may ask? I just today had the same issues and had to manually change the group of the mounted volumes as there is no default security context set. 

The read-only config is also quite problematic and even trying to migrate it into the database configuration as described in the documentation is not possible as the migration fails because the config is readonly

2021-05-03 20:22 UTC, sotolucas commented
hey there @mrparkers !
In some cases, the config persistence size value of 50MiB seem not to work.
When I set it to 1Gi for example, it works fine.
I'm using DigitalOcean Kubernetes Service.
Anyway that's the only thing I would change, but apart from that everything else LGTM.

2021-05-12 09:53 UTC, cpanato requested changes
thanks for this change

can you split the PR in two? one for TE and another for EE

thanks!

2021-05-16 23:52 UTC, ahmaddanialmohd commented
A customer mentioned that they were able to solve it by creating a separate mount point. A question that they have here is whether it is possible to temporarily apply **extraInitContainers** like in the following link:

* [[mattermost-team-edition] read only file system on start up #100
](https://github.com/mattermost/mattermost-helm/issues/100)

2021-05-28 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-06-08 06:07 UTC, syuo7 commented
Hello.
When plan this PR be merged?
I'm looking forward to resolving this issue.

Thank you.

2021-06-08 10:55 UTC, jasonblais commented
@cpanato why do we want to split the PR into two, any harm in keeping it in one and reviewing/merging?

2021-06-09 07:09 UTC, cpanato commented
@jasonblais because the automation for the release of the charts only supports one chart being updated at time per PR, and also helps to track down the changes

2021-06-13 01:15 UTC, jasonblais commented
@cpanato I split out the changes to
 - enterprise-edition: https://github.com/mattermost/mattermost-helm/pull/223
 - team-edition: https://github.com/mattermost/mattermost-helm/pull/224

@mrparkers Huge thanks for your contribution! I hope it was okay for me to split your changes into the above two PRs. Currently, our automation for the release of the charts only supports one chart being updated at time per PR. If you'd prefer to make the split yourself, feel free to do so, and I'll close mine.

Hope we get these excellent changes merged soon. :)

2021-06-14 09:10 UTC, cpanato commented
closing this PR in favor or the ones that Jason opened

2021-06-14 09:10 UTC, closed without merging

2021-06-14 22:17 UTC, mrparkers commented
No problem at all, I didn't have the bandwidth to redo this so I'm happy these changes were able to make their way in somehow.  Thanks for the initiative!