Fix a typo in documentation
mattermost/mattermost-helm pull request #227
Opened 2021-06-17 13:28 UTC by oh6hay

I assume that is a typo

2021-06-17 13:28 UTC, mattermod commented
Hello @oh6hay,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-06-25 10:30 UTC, cpanato requested changes
thanks for fixing this

can you bump the chart version?

2021-07-03 18:50 UTC, oh6hay commented
sure, like this?

2021-07-14 01:00 UTC, mattermod commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

/cc @jasonblais @jfrerich @emilyacook

2021-07-14 08:48 UTC, cpanato approved these changes

2021-07-14 08:48 UTC, merged