Feature/private registry
mattermost/mattermost-helm pull request #290
Opened 2022-01-13 14:01 UTC by patatman

#### Summary

PR makes it possible to pull operator images from a private registry, when needing to authenticate. 
Added additional field to supply a Secret name where the Registry Credentials are located in the namespace. 

Documentation needs to be clarified a bit I think to make sure people don't make mistakes. 

#### Ticket Link

Fixes https://github.com/mattermost/mattermost-helm/issues/233

2022-01-13 14:20 UTC, cpanato requested changes
thanks for the PR and the improvement

can you bump the chart version, check a small comment and squash the commit into one?

2022-01-13 15:20 UTC, patatman commented on charts/mattermost-operator/values.yaml
> +    imagePullSecret: regcred
Resolved in the latest commit

2022-01-13 16:00 UTC, cpanato commented
> For some reason I can't seem to remove one of my commits, I've tried rebasing, but it keeps popping back. Maybe because of the change we did simultaneously? I needed to fetch my forked branch to make it work.

you can rebase and then squash the commits, you can use the `git rebase -i upstream/master` to help the `-i` is interactive

2022-01-13 16:30 UTC, patatman commented
I did a hard reset to master, and then just reapplied the changes. Looks like everything is clean now :)

2022-01-14 10:06 UTC, cpanato approved these changes

2022-01-14 10:24 UTC, Szymongib approved these changes
LGTM

2022-01-14 10:32 UTC, stylianosrigas approved these changes
Good stuff thanks a lot 🚀

2022-01-14 11:38 UTC, merged