add extraEnv to jobserver values for libpq PG* variables
mattermost/mattermost-helm pull request #316
Opened 2022-03-17 14:23 UTC by ruckc

#### Summary

This PR adds `extraEnv` array to the jobserver configuration in order to set various environment variables for mattermost.

In short, when using an external postgres, with `driverName: postgres`, you can leave datasource as an empty string, and use `extraEnv` to pass [libpq environment variables](https://www.postgresql.org/docs/current/libpq-envars.html) to the mattermost process.  Some of these can be pulled from secrets.

#### Ticket Link

This PR partially addresses [#140](https://github.com/mattermost/mattermost-helm/issues/140), when using an external postgresql database.

#### Values example

When using mattermost paired with [Postgres Operator](https://postgres-operator.readthedocs.io/en/latest/)

```yaml
extraEnv:
  - name: PGHOST
    value: mattermost-database.mattermost.svc.cluster.local
  - name: PGPORT
    value: "5432"
  - name: PGDATABASE
    value: mattermost
  - name: MM_LDAPSETTINGS_BINDUSERNAME
    valueFrom:
      secretKeyRef:
        key: dn
        name: ldap-credentials
  - name: MM_LDAPSETTINGS_BINDPASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: ldap-credentials
  - name: PGUSER
    valueFrom:
      secretKeyRef:
        key: username
        name: mattermost.mattermost-database.credentials.postgresql.acid.zalan.do
  - name: PGPASSWORD
    valueFrom:
      secretKeyRef:
        key: password
        name: mattermost.mattermost-database.credentials.postgresql.acid.zalan.do
```

2022-03-17 14:23 UTC, mattermod commented
Hello @ruckc,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2022-03-24 14:04 UTC, ruckc commented
@stylianosrigas  - can you look at this PR please?

2022-03-24 14:11 UTC, spirosoik reviewed
other than comment, looks good

2022-03-24 14:30 UTC, ruckc commented on charts/mattermost-enterprise-edition/templates/deployment-mattermost-jobserver.yaml
> +{{- with .Values.global.features.jobserver.extraEnv }}
I was mimicking the indentation format from deployment-mattermost-app.yaml.  This is addressed.

2022-03-24 14:30 UTC, ruckc commented
@pfltdv - should i bump the version also?  that is why one of the lint-charts is failing

2022-03-24 14:43 UTC, pfltdv commented
> @pfltdv - should i bump the version also? that is why one of the lint-charts is failing

@ruckc It should not be a requirement for you since we are not generating a release. Looks like the versions at master branch need to be fixed. I will check, fix and notify you as soon as it is ready.

2022-03-24 15:10 UTC, pfltdv requested changes
@ruckc Unfortunately we need to do version bumps on your branch. Please update chart versions to have successful CI and release process after. I will create different ticket to improve our processes for helm charts.

enterprise: 2.4.5
team: 6.5.1

2022-03-24 15:39 UTC, stylianosrigas approved these changes
LGTM, thanks @ruckc

2022-03-25 22:46 UTC, ruckc commented
@pfltdv / @stylianosrigas - when will this be merged?

2022-03-28 06:15 UTC, merged