Added startupProbe
mattermost/mattermost-helm pull request #407
Opened 2023-07-06 05:22 UTC by mustdiechik

Added startupProbe 

- to increase start speed up.
- best practice
- some migrations can takes a long time and initialDelaySeconds=90 for livenessProbe maybe a little.

2023-07-06 05:22 UTC, mattermost-build commented
Hello @mustdiechik,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

Per the [Mattermost Contribution Guide](https://developers.mattermost.com/contribute/getting-started/), we need to add you to the list of [approved contributors](https://docs.google.com/spreadsheets/d/1NTCeG-iL_VS9bFqtmHSfwETo5f-8MQ7oMDE5IUYJi_Y/pubhtml?gid=0&single=true) for the Mattermost project.

**Please help complete the Mattermost [contribution license agreement](http://www.mattermost.org/mattermost-contributor-agreement/)?**
Once you have signed the CLA, please comment with `/check-cla` and confirm that the CLA check is green.

This is a standard procedure for many open source projects.

Please let us know if you have any questions.

We are very happy to have you join our growing community! If you're not yet a member, please consider joining our [Contributors community channel](https://pre-release.mattermost.com/core/channels/tickets) to meet other contributors and discuss new opportunities with the core team.

2023-07-06 05:30 UTC, mustdiechik commented
/check-cla

2023-07-11 14:14 UTC, stafot commented
@mustdiechik In my view these values (`failureThreshold`,`periodSeconds`,`initialDelaySeconds`,`timeoutSeconds`) shouldn't be hardcoded in the template. You could follow the approach we have on this [PR](https://github.com/mattermost/mattermost-helm/pull/408).

2023-07-12 13:34 UTC, spirosoik commented
+1 on what @stafot mentioned

2023-07-12 13:35 UTC, spirosoik requested changes

2023-07-12 13:35 UTC, spirosoik commented on charts/mattermost-team-edition/templates/deployment.yaml
> +          failureThreshold: 20
let's make these dynamic values instead of static values here.

2023-07-12 15:12 UTC, stafot requested changes
COnsider my comment

2023-07-13 06:20 UTC, spirosoik commented
@mustdiechik looks good. Did you sign the CLA? Seems that there's still an issue

2023-07-13 06:32 UTC, mustdiechik commented
/check-cla

2023-07-13 11:31 UTC, stafot commented
@mustdiechik CLA looks good to me unsure why it fails. Although you need to resolve conflicts on this PR

2023-07-13 12:03 UTC, mustdiechik commented
@stafot check please

2023-07-13 13:24 UTC, stafot approved these changes
LGTM

2023-07-14 07:10 UTC, mustdiechik commented
@spirosoik ^^

2023-07-14 08:53 UTC, spirosoik commented
@mustdiechik let's have a similar PR for the enterprise edition too. It will be valuable there too.

2023-07-14 08:53 UTC, spirosoik approved these changes
Great work. Thanks for your contribution

2023-07-14 08:54 UTC, merged