fix security context at container level in hardened k8s cluster
mattermost/mattermost-helm pull request #482
Opened 2024-11-15 13:56 UTC by jm-bertheas-datailor

#### Summary
When we try to deploy [mattermost-team-edition] with helm charts into a hardened k8s cluster, it's not possible to define a custom securityContext at the container level (event if it's possible at pod level but it's not enough to start the mattermost-team-edition pod).
We have to add some custom securityContext definition on the deployment at the container level.

The fix done here, is supposed to be backward compatible.

#### Ticket Link
  Fixes https://github.com/mattermost/mattermost-helm/issues/315

2024-11-15 13:56 UTC, mattermost-build commented
Hello @jm-bertheas-datailor,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2024-11-26 01:03 UTC, mattermost-build commented
This PR has been automatically labelled "stale" because it hasn't had recent activity.
A core team member will check in on the status of the PR to help with questions.
Thank you for your contribution!

2025-03-11 05:00 UTC, Ansible-man commented
Is this going to get merged?

2025-04-19 13:32 UTC, stafot commented
@jm-bertheas-datailor 
Thanks for the PR — this looks great overall and I really appreciate the effort to align the naming with common conventions.

I do prefer `podSecurityContext` as it's more explicit and matches standard Kubernetes terminology. That said, I have a small concern about backward compatibility — since `securityContext` was previously used for the pod-level context, some users might be relying on that key in their existing `values.yaml` overrides.

To maintain compatibility, would it make sense to keep `securityContext` as-is for pod-level settings and introduce something like `containerSecurityContext` or `defaultContainerSecurityContext`  for the new container-level one?

Curious to hear your thoughts — I'm very much in favor of this PR and happy to approve it once we align on this detail.

cc @timstott

2025-04-20 15:45 UTC, timstott commented
Thanks for following up @stafot. The `podSecurityContext` and container `securityContext` share common properties but also have exclusive ones. The changes currrently proposed would be a breaking change.

I see two options available to us:

1. Introduce the breaking change. We can improve the upgrade experience [by failing](https://masterminds.github.io/sprig/flow_control.html) when an incompatible property exists on `securityContext`. 
2. Or as proposed add the `containerSecurityContext` setting.

I am happy to contribute to either solutions. The decision may come down to the mattermost's team policy.

2025-04-22 12:42 UTC, gabrieljackson commented
Great conversation here. After thinking about this a bit, I am also in favor of modifying the implementation so that we don't possibly introduce a breaking change for existing users. If we had to build a larger workaround to support them I would would say to proceed with this change, but all we need to do here is select a slightly different name for the container security context so that gets my vote.

2025-04-22 16:52 UTC, stafot requested changes
Let's refactor this PR based on proposal nr.2

2025-04-23 12:18 UTC, toninis commented
@timstott @jm-bertheas-datailor my two cents here . 

We can keep the existing functionality with securityContext and also add it on the container level (it won't make a difference). 
Create the new `podSecurityContext` which will precede `securityContext` if it exists

2025-04-25 23:18 UTC, timstott commented
@gabrieljackson @stafot Thank you for your support. I have updated the implementation in https://github.com/mattermost/mattermost-helm/pull/498

2025-04-27 23:15 UTC, closed without merging